DATASET:
  ROOT: "data"
  SMALLEST_RANGE: [256,256]
  RND_CROP: False
  RND_ZOOM: True
  RND_ZOOM_RANGE: [.5, 1.]
  GUIDED_HFLIP: True
  VIDEO_LEN: 5
  FRAME_GAP: 10
  MP4: True
TRAIN:
  BATCH_SIZE: 16
  NUM_EPOCHS: 80
  TASK: "kinetics400"
MODEL:
  LR: 0.001
  CE_REF: 0.1
  OPT: "SGD"
  LR_SCHEDULER: "step"
  LR_GAMMA: 0.5
  LR_STEP: 20
  WEIGHT_DECAY: 0.0005
LOG:
  ITER_TRAIN: 8
  ITER_VAL: 2
TEST:
  KNN: 10
  CXT_SIZE: 20
  RADIUS: 12
  TEMP: 0.05
TB:
  IM_SIZE: [196, 196]
