DATASET:
#  ROOT: r"/cpfs01/user/aiforscience2/kjq/dataset/vos/train"
#  ROOT: r"D:\BaiduNetdiskDownload\vos\all_frames\train_all_frames_zip\train_all_frames\train_all_frames"
  ROOT: r"/root/autodl-tmp/dataset/vos/train"
  SMALLEST_RANGE: [256, 320]
  RND_CROP: True
  RND_ZOOM: True
  RND_ZOOM_RANGE: [.5, 1.]
  GUIDED_HFLIP: True
  VIDEO_LEN: 5
  FRAME_GAP: 2
TRAIN:
  BATCH_SIZE: 8
  NUM_EPOCHS: 500
  TASK: "YTVOS"
MODEL:
  LR: 0.0001
  OPT: "Adam"
  LR_SCHEDULER: "step"
  LR_GAMMA: 0.5
  LR_STEP: 100
  WEIGHT_DECAY: 0.0005
LOG:
  ITER_TRAIN: 20
  ITER_VAL: 10
TEST:
  KNN: 10
  CXT_SIZE: 20
  RADIUS: 12
  TEMP: 0.05
TB:
  IM_SIZE: [196, 196]
